all:
	python3 knn_cross_validation.py  
	python3 svm.py                   
	python3 bagging.py   
	python3 knn_best_values.py  
	python3 random_forest.py         
	python3 svm_cross_validation.py